name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        TAG_NAME: "cdev:$(date +%s)"
      run: |
       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker build . --file Dockerfile --tag $TAG_NAME
       docker push marshallasch/$TAG_NAME
